### ISSUE TITLE
Move header and footer bits inside the shell

### ISSUE THREAD

**Issue by mcdonnelldean** [rjrodger/nodezoo-web#20]
This means we end up with 

```
<div id=app>
 <div className=shell>
  ... Whole site here
```

I'm not massively happy about this but I need to speak to people with more react experience to fix. For now this will allow @thefoxis to keep the design semantic so we can just pull the two top divs when we figure out the best way to do it.

@ckiss I'll get you to do this for Nodezoo please.

**Comment by mcdonnelldean** [comment]
@ckiss Hold till Monday

**Comment by ckiss** [comment]
done by: https://github.com/rjrodger/nodezoo-web/pull/23
