### ISSUE TITLE
How to run instructions should be improved

### ISSUE THREAD

**Issue by thefoxis** [rjrodger/nodezoo-web#3]
Like so:

## How to run

1. install dependencies: `npm i` and `bower install`
2. run the service: `node srv/app-dev.js`
3. open [http://localhost:8000/](http://localhost:8000/)

**Comment by mcdonnelldean** [comment]
@thefoxis Fully agree,

I'm going to drop bower too. Ideally I would like each service to run as simply as `npm install`, then `npm run`. Once I have this done I will update the instructions to be simpler.

**Comment by thefoxis** [comment]
Yes, that'd be probably optimal. You could also do pre- or postprocessing (mostly for variables sake, but plain CSS is a-okay too), concatenate CSS files and run other optimisation tasks; but if it's supposed to only be mostly for demonstration purposes I probably would leave that out.

**Comment by mcdonnelldean** [comment]
Actually I have this as an action item to get your opinion on 😊 let's discuss this too

**Comment by mcdonnelldean** [comment]
Done in `to-redux`
