### ISSUE TITLE
UI Refresh

### ISSUE THREAD

**Issue by mcdonnelldean** [rjrodger/nodezoo-web#6]
Hey @thefoxis 

I added notes below. You can do all this on your static fork, I wasn't able to open an issue there so I stook it here. I'm happy for you to convert to stylus too if you want, you don't need to set up a pipeline, it's fine to manually run the process, I'll automate it when when I move it in.

If you have changes to the header feel free to bring em in.

![attachment-2](https://cloud.githubusercontent.com/assets/3625961/12341118/39c9a660-bb17-11e5-9e92-84d49b31b4c5.png)

- Make the search bar wider, button size is perfect
- In the module list, use the three samples provided below
- Removed the body text in each list item
- Add in the a hex logo for each list item using the rating

![attachment-3](https://cloud.githubusercontent.com/assets/3625961/12341103/2b878e50-bb17-11e5-9f54-d3af109a7510.png)

- Update the npm section to match the sample data
- Add the github section same as the npm section
- Style the items in each section to have a bigger header and no bullet.
- Add a refresh icon to the blue bar / remove the button, I'm going to use this if slow loading
- Make the module name larger and stand out more
- Add npm and github icons beside the header

## Data - npm

name: seneca
version: 1.0.0
created: 01/01/2013
url: npmjs.com/seneca
rating: 4

name: seneca-user
version: 0.4.2
created: 01/04/2014
url: npmjs.com/seneca-user
rating: 2

name: seneca-auth
version: 0.5.3
created: 01/05/2013
url: npmjs.com/seneca
rating: 3

## Data - Github

name: seneca
version: 1.0.0
created: 01/01/2013
url: github.com/senecajs/seneca
rating: 4

name: seneca-user
version: 0.4.2
created: 01/04/2014
url: github.com/senecajs/seneca-user
rating: 2

name: seneca-auth
version: 0.5.3
created: 01/05/2013
url: github.com/senecajs/seneca-auth
rating: 3

**Comment by mcdonnelldean** [comment]
@thefoxis If you need anything else just ping me.

**Comment by thefoxis** [comment]
everything is in the fork, right [here](https://github.com/thefoxis/nodezoo-web/tree/i01). I believe that all of the points were addressed, there are two results on the index page, just to show it off and then one module on info page (seneca) with its' github and npm information. let me know what you think!

**Comment by mcdonnelldean** [comment]
@thefoxis Just reviewed, this looks good :D I'm going to pull this over as the Redux bits come online.
